### ISSUE TITLE
Using GPIO 4 for TX LED

### ISSUE THREAD

**Issue by dk8hc** [oe3cjb/TTGO-T-Beam-LoRa-APRS#12]
Hi, by using GPIO 4 the onboard LED can be used for TX LED and an external LED can be connected, too. Rev. 1 ![IMG_20210129_230651.jpg](https://user-images.githubusercontent.com/77748633/106332236-af3bbe80-6286-11eb-810a-e6108e0bd193.jpg) ![IMG_20210130_020110.jpg](https://user-images.githubusercontent.com/77748633/106341844-077eba80-629f-11eb-8281-71781706bfce.jpg)

**Comment by oe3cjb** [comment]
Thank you for this idea - definitely worth to change the code accordingly! Will be updated soon!

**Comment by dk8hc** [comment]
Thank you, pse correct it in the description of "readme.md" to prevent inquiries ;-)

**Comment by oe3cjb** [comment]
erledigt :-)
