### ISSUE TITLE
Using APRS_SYMBOL while Tracking

### ISSUE THREAD

**Issue by dk8hc** [oe3cjb/TTGO-T-Beam-LoRa-APRS#15]
An option would be great to use the chosen APRS_SYMBOL with normal callsign while using WX-Tracker Mode and use only WX SSID and WX symbol while using WX_Move and WX_Fixed

**Comment by oe3cjb** [comment]
Thank you for the idea!
When using normal symbol at WX Tracker mode WX data is not sown as this is recognized by the WX symbol - therefor I will keep it as it is.
