### ISSUE TITLE
TTGO-T-Beam-LoRa-APRS-trackermode_correction -> New issue...

### ISSUE THREAD

**Issue by cyberknol** [oe3cjb/TTGO-T-Beam-LoRa-APRS#16]
Hello Christian,
In advance I was able to show you that the T-Beam did boot up in "Tracker / WX mode". Terminal data did show that, and indeed the WX broadcast did pop up in APRS.fi. Unfortunately the Tracker broadcast does not show up anymore. It does show up when I set Tracker mode to 0. 

So:
PA1SDB-9 tracker is silence
PA1SDB-8 WX transmits every 15 minutes.

#define DONT_USE_FLASH_MEMORY 
#define TRACKERMODE 1
#define CALLSIGN "PA1SDB-9"
#define WX_CALLSIGN "PA1SDB-8" 
#define LONGITUDE_PRESET "0651,18E"
#define LATIDUDE_PRESET "5319.14N"
#define APRS_SYMBOL ">" 
 
  73s Peter

**Comment by oe3cjb** [comment]
Hi Peter,
it seems that soem bytes in the package where missing - I added them - please give it a try.
73 Christian OE3CJB

**Comment by cyberknol** [comment]
O.k. thanks for message. I'll try when I have time.

73s Peter de PA1SDB


Op do 13 mei 2021 10:49 schreef oe3cjb ***@***.***>:

**Comment by oe3cjb** [comment]
seems to be fixed
