### ISSUE TITLE
Fixing TX_BASE91 warnings

### ISSUE THREAD

**Issue by df1oe** [oe3cjb/TTGO-T-Beam-LoRa-APRS#18]
Hallo Christian, ich habe nur eine kleine Änderung, damit es ein paar weniger warnungen gibt...just refactoring
[TTGO_T-Beam_LoRa_APRS.zip](https://github.com/oe3cjb/TTGO-T-Beam-LoRa-APRS/files/6068413/TTGO_T-Beam_LoRa_APRS.zip)

**Comment by oe3cjb** [comment]
Hi, könntest Du die Änderungen bitte in einem neuen Branch aufmachen und einen Pull Request stellen? Besten Dank :-)
