### ISSUE TITLE
APRS TX of Battery Voltage in 'WX_FIXED' Mode?

### ISSUE THREAD

**Issue by K4KDR** [oe3cjb/TTGO-T-Beam-LoRa-APRS#21]
Just updated to e2077e4, THANK YOU so much for adding pressure to the weather data!

I have been using '**WX_TRACKER**' mode so that every-other TX would include battery voltage.  But in hopes of prolonging battery life, switched to '**WX_FIXED**' mode to turn off the GPS.

I would still very much like to see battery voltage in the telemetry, and discovered:

`#define HW_COMMENT              // send Alt und Battery Voltage, UNcomment if you want to send it`

... so with that UNcommented, I was hoping to see battery voltage in the APRS message.

Unfortunately, while **MY_COMMENT** text comes through fine, I never see any mention of battery voltage.

Here is how my messages are appearing on APRS-IS:

`2021-05-30 14:05:15 EDT: K4KDR-13>APRS,qAS,K4KDR-14:!3746.70N/07736.55W_.../...g...t069r...p...P...h59b10223_433.775 LoRa APRS + WX`

... am I missing a step, or not understanding the proper use of **HW_COMMENT**?

For reference, when I was using '**WX_TRACKER**' mode, the battery voltage was reported perfectly under SSID 'K4KDR-4'.

`2021-05-29 20:12:45 EDT: K4KDR-4>APRS,qAS,K4KDR-14:!/;E4O:pzU_!!H/A=000274 Batt=3.50V_433.775 LoRa APRS + WX`

Thank you VERY much for any assistance!

-Scott,  K4KDR

**Comment by K4KDR** [comment]
One follow-up...

In the serial monitor, I notice that battery voltage IS reported in this config.  So, no issue there but of course it would be wonderful to see it via APRS, too.

```
((TX)) / LAT: 3746.70N / LON: 07736.55W / No GPS used / SAT: --- / BAT: 4.2 / TEMP: 20.6 / HUM: 58.6
State: Packet sent!
```

**Comment by K4KDR** [comment]
I found how I could add the battery voltage to my APRS "Comment" when using mode = WX_FIXED and am happy with the result:

`2021-05-30 22:19:52 EDT: K4KDR-13>APRS,qAS,K4KDR-14:!3746.70N/07736.55W_.../...g...t071r...p...P...h58b10257_433.775 LoRa APRS + WX -- Batt=4.18V`

... please see for reference:

https://github.com/oe3cjb/TTGO-T-Beam-LoRa-APRS/pull/22/commits/77f2067950e92e295069834b595dd7db03cab92a

**Comment by oe3cjb** [comment]
thank you for playing around with my code which I wrote during the x-mas holiday season in Dec 2019 - it was planned to be the base for other APRS operators - so this happened and I am very happy about that :-)
