### ISSUE TITLE
LoRa packet header documentation

### ISSUE THREAD

**Issue by ge0rg** [oe3cjb/TTGO-T-Beam-LoRa-APRS#24]
Hi, I was wondering about the on-the-wire-format of LoRa packets containing APRS.

It looks like [this code is generating the header](https://github.com/oe3cjb/TTGO-T-Beam-LoRa-APRS/blob/master/lib/BG_RF95/BG_RF95.cpp#L301-L303), consisting of:
- verbatim `"<"`
- sender's ID (byte) - is that ever initialized anywhere?
- `0x01` byte

What is the meaning of the "<" and of the 0x01? It _looks like_ the regular LoRa header is four bytes (to, from, ID, flags) - why is the APRS header shorter? Why are we not using to=0xff (broadcast)?

**Comment by oe3cjb** [comment]
this was just copied from another code and so I don't know :-(
